<<<<<<< HEAD
---
name: Paladin Prototypes
author: Paulo Silva
url: "https://www.linkedin.com/in/paulopath/"
=======
name: Paladin Prototypes
author: Paulo Silva
url: https://www.linkedin.com/in/paulopath/
>>>>>>> c9bf7c17e093adf5406844f1e2cac4a2bd8f3125
